FROM node:20 AS base
# From https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile


# # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
# RUN apk add --no-cache libc6-compat
WORKDIR /code

COPY . .
RUN npm install

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "run", "dev"]
