import { UserfrontProvider } from "@userfront/next/client";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Userfront + Nextjs + Golang",
  description: "Generated by Userfront",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserfrontProvider tenantId={process.env.NEXT_PUBLIC_USERFRONT_WORKSPACE_ID}>
          <div>
            <Link href="/">Home</Link>
          </div>
          {children}
        </UserfrontProvider>
      </body>
    </html>
  );
}
