version: '3.8'
services:
  backend:
    container_name: fastapi
    build: ./backend
    env_file:
      - .env.local
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/code
  frontend:
    container_name: nextjs
    build: ./frontend
    env_file:
      - .env.local
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
